name: radial_button_sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  radial_button:
    git:
      url: https://github.com/viniciusoliverrs/radial_button

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutterando_analysis: ^0.0.2

flutter:
  uses-material-design: true